import type { KernelParamInfo, ConfigHint } from "./k8s-client"

// sysctl 파일 경로는 파라미터에 따라 다름.
const SPECIAL_HINT_LOCATIONS: Record<string, string> = {
  "net.bridge.bridge-nf-call-iptables":  "/etc/sysctl.d/k8s-network.conf",
  "net.bridge.bridge-nf-call-ip6tables": "/etc/sysctl.d/k8s-network.conf",
  "net.ipv4.ip_forward":                 "/etc/sysctl.d/k8s-network.conf",
  "net.ipv6.conf.all.disable_ipv6":      "/etc/sysctl.d/k8s-disable-ipv6.conf",
  "net.ipv6.conf.default.disable_ipv6":  "/etc/sysctl.d/k8s-disable-ipv6.conf",
  "net.ipv6.conf.lo.disable_ipv6":       "/etc/sysctl.d/k8s-disable-ipv6.conf",
}

function hint(param: string, value: string): ConfigHint {
  return {
    location: SPECIAL_HINT_LOCATIONS[param] ?? "/etc/sysctl.d/99-k8s-tuning.conf",
    command: `sudo sysctl -w ${param}="${value}"`,
    docLink: "https://github.com/dasomel/kube-ready-box/blob/main/packer/scripts/02-os-tuning.sh",
    autoApply: "node-ssh",
  }
}

type RawKernelParam = Omit<KernelParamInfo, "configHint">

// kube-ready-box 적용값(current) vs K8s 프로덕션 권장값(recommended)
// 미설정 항목만 Ubuntu 24.04 기본값으로 표시
const RAW_PARAMS: RawKernelParam[] = [
  // ── Network ─────────────────────────────────────────────────────────────
  { param: "net.core.somaxconn",                               currentValue: "65535",          recommendedValue: "65535",          group: "network",    description: { ko: "소켓 연결 대기열 최대 크기", en: "Max socket connection backlog" }, impact: { ko: "고부하 접속 지연/거부 방지", en: "Prevents connection delay/rejection under high load" } },
  { param: "net.core.netdev_max_backlog",                      currentValue: "65535",          recommendedValue: "65535",          group: "network",    description: { ko: "NIC 수신 패킷 대기 큐 크기", en: "NIC receive queue size" }, impact: { ko: "패킷 드롭 및 네트워크 병목 방지", en: "Prevents packet drops and network bottlenecks" } },
  { param: "net.core.rmem_max",                                currentValue: "16777216",       recommendedValue: "16777216",       group: "network",    description: { ko: "소켓 수신 버퍼 최대 크기 (16MB)", en: "Max socket receive buffer (16MB)" }, impact: { ko: "고대역폭 워크로드 처리율 향상", en: "Improves throughput for high-bandwidth workloads" } },
  { param: "net.core.wmem_max",                                currentValue: "16777216",       recommendedValue: "16777216",       group: "network",    description: { ko: "소켓 송신 버퍼 최대 크기 (16MB)", en: "Max socket send buffer (16MB)" }, impact: { ko: "고대역폭 워크로드 처리율 향상", en: "Improves throughput for high-bandwidth workloads" } },
  { param: "net.core.rmem_default",                            currentValue: "262144",         recommendedValue: "262144",         group: "network",    description: { ko: "소켓 수신 버퍼 기본 크기 (256KB)", en: "Default socket receive buffer (256KB)" }, impact: { ko: "소규모 소켓에서 수신 버퍼 기본값 확보", en: "Ensures adequate receive buffer default for small sockets" } },
  { param: "net.core.wmem_default",                            currentValue: "262144",         recommendedValue: "262144",         group: "network",    description: { ko: "소켓 송신 버퍼 기본 크기 (256KB)", en: "Default socket send buffer (256KB)" }, impact: { ko: "소규모 소켓에서 송신 버퍼 기본값 확보", en: "Ensures adequate send buffer default for small sockets" } },
  { param: "net.ipv4.tcp_rmem",                                currentValue: "4096 262144 16777216", recommendedValue: "4096 262144 16777216", group: "network", description: { ko: "TCP 수신 버퍼 (min default max)", en: "TCP receive buffer (min default max)" }, impact: { ko: "TCP 스트림 처리량 최적화", en: "Optimizes TCP stream throughput" } },
  { param: "net.ipv4.tcp_wmem",                                currentValue: "4096 262144 16777216", recommendedValue: "4096 262144 16777216", group: "network", description: { ko: "TCP 송신 버퍼 (min default max)", en: "TCP send buffer (min default max)" }, impact: { ko: "TCP 스트림 처리량 최적화", en: "Optimizes TCP stream throughput" } },
  { param: "net.ipv4.tcp_max_syn_backlog",                     currentValue: "65535",          recommendedValue: "65535",          group: "network",    description: { ko: "TCP SYN 연결 대기열 크기", en: "TCP SYN backlog queue size" }, impact: { ko: "SYN flood 대응 및 연결 큐 안정화", en: "SYN flood defense and stable connection queue" } },
  { param: "net.ipv4.tcp_tw_reuse",                            currentValue: "1",              recommendedValue: "1",              group: "network",    description: { ko: "TIME_WAIT 소켓 재사용", en: "Reuse TIME_WAIT sockets" }, impact: { ko: "포트 고갈 방지, 연결 효율 향상", en: "Prevents port exhaustion and improves connection efficiency" } },
  { param: "net.ipv4.tcp_fin_timeout",                         currentValue: "15",             recommendedValue: "15",             group: "network",    description: { ko: "FIN_WAIT_2 소켓 대기 시간(초)", en: "FIN_WAIT_2 socket timeout (seconds)" }, impact: { ko: "불필요한 소켓 점유 시간 단축", en: "Reduces unnecessary socket hold time" } },
  { param: "net.ipv4.tcp_keepalive_time",                      currentValue: "300",            recommendedValue: "300",            group: "network",    description: { ko: "TCP Keepalive 첫 프로브 간격(초)", en: "TCP keepalive initial probe interval (seconds)" }, impact: { ko: "유휴 연결 조기 감지, 리소스 절약", en: "Early detection of idle connections, saves resources" } },
  { param: "net.ipv4.tcp_keepalive_probes",                    currentValue: "5",              recommendedValue: "5",              group: "network",    description: { ko: "TCP Keepalive 프로브 재시도 횟수", en: "TCP keepalive probe retry count" }, impact: { ko: "연결 단절 감지 속도와 신뢰성 균형", en: "Balances connection failure detection speed and reliability" } },
  { param: "net.ipv4.tcp_keepalive_intvl",                     currentValue: "15",             recommendedValue: "15",             group: "network",    description: { ko: "TCP Keepalive 프로브 간격(초)", en: "TCP keepalive probe interval (seconds)" }, impact: { ko: "연결 단절 빠른 감지", en: "Fast detection of connection failures" } },
  { param: "net.ipv4.tcp_mtu_probing",                         currentValue: "1",              recommendedValue: "1",              group: "network",    description: { ko: "MTU 자동 탐색 활성화", en: "Enable automatic MTU probing" }, impact: { ko: "블랙홀 라우터 우회, 연결 복원력", en: "Bypasses black-hole routers, improves connection resilience" } },
  { param: "net.ipv4.tcp_syncookies",                          currentValue: "1",              recommendedValue: "1",              group: "network",    description: { ko: "SYN Flood 방지 (SYN Cookie)", en: "SYN flood protection (SYN cookie)" }, impact: { ko: "DDoS SYN flood 방어", en: "Defends against DDoS SYN flood attacks" } },
  { param: "net.ipv4.ip_forward",                              currentValue: "1",              recommendedValue: "1",              group: "network",    description: { ko: "IP 패킷 포워딩 (K8s 필수)", en: "IP packet forwarding (K8s required)" }, impact: { ko: "Pod 간 통신 필수 설정", en: "Required for inter-pod communication" } },
  { param: "net.ipv4.neigh.default.gc_thresh1",                currentValue: "4096",           recommendedValue: "4096",           group: "network",    description: { ko: "ARP 캐시 가비지 컬렉션 하한 임계값", en: "ARP cache GC low threshold" }, impact: { ko: "대규모 클러스터 ARP 브로드캐스트 방지", en: "Prevents ARP broadcast storms in large clusters" } },
  { param: "net.ipv4.neigh.default.gc_thresh2",                currentValue: "8192",           recommendedValue: "8192",           group: "network",    description: { ko: "ARP 캐시 소프트 상한 임계값", en: "ARP cache soft upper threshold" }, impact: { ko: "Neighbor 테이블 GC 빈도 제어", en: "Controls neighbor table garbage collection frequency" } },
  { param: "net.ipv4.neigh.default.gc_thresh3",                currentValue: "16384",          recommendedValue: "16384",          group: "network",    description: { ko: "ARP 캐시 최대 항목 수 (하드 상한)", en: "Max ARP cache entries (hard limit)" }, impact: { ko: "대규모 클러스터 ARP 브로드캐스트 방지", en: "Prevents ARP broadcast storms in large clusters" } },
  { param: "net.netfilter.nf_conntrack_max",                   currentValue: "1048576",        recommendedValue: "1048576",        group: "network",    description: { ko: "Netfilter 연결 추적 테이블 최대 크기", en: "Max netfilter connection tracking table size" }, impact: { ko: "대규모 클러스터 conntrack 고갈 방지", en: "Prevents conntrack table exhaustion in large clusters" } },
  { param: "net.netfilter.nf_conntrack_tcp_timeout_established", currentValue: "86400",        recommendedValue: "86400",          group: "network",    description: { ko: "확립된 TCP 연결 추적 타임아웃(초)", en: "Established TCP connection tracking timeout (seconds)" }, impact: { ko: "장기 연결 끊김 방지", en: "Prevents long-lived connections from being dropped" } },
  { param: "net.netfilter.nf_conntrack_tcp_timeout_close_wait", currentValue: "3600",          recommendedValue: "3600",           group: "network",    description: { ko: "CLOSE_WAIT 상태 연결 추적 타임아웃(초)", en: "CLOSE_WAIT connection tracking timeout (seconds)" }, impact: { ko: "반열린 연결 테이블 누적 방지", en: "Prevents half-open connection table accumulation" } },
  { param: "net.bridge.bridge-nf-call-iptables",               currentValue: "1",              recommendedValue: "1",              group: "network",    description: { ko: "브리지 트래픽에 iptables 적용 (K8s 필수)", en: "Apply iptables to bridge traffic (K8s required)" }, impact: { ko: "K8s NetworkPolicy 및 kube-proxy 정상 동작", en: "Required for K8s NetworkPolicy and kube-proxy to function" } },
  { param: "net.bridge.bridge-nf-call-ip6tables",              currentValue: "1",              recommendedValue: "1",              group: "network",    description: { ko: "브리지 트래픽에 ip6tables 적용 (K8s 필수)", en: "Apply ip6tables to bridge traffic (K8s required)" }, impact: { ko: "K8s IPv6 NetworkPolicy 정상 동작", en: "Required for K8s IPv6 NetworkPolicy to function" } },
  // ── Security ────────────────────────────────────────────────────────────
  { param: "net.ipv4.conf.all.rp_filter",                      currentValue: "1",              recommendedValue: "1",              group: "security",   description: { ko: "역방향 경로 필터링 (IP Spoofing 방지)", en: "Reverse path filter (anti-spoofing)" }, impact: { ko: "네트워크 레벨 소스 주소 위조 차단", en: "Blocks network-level source address spoofing" } },
  { param: "net.ipv4.conf.default.rp_filter",                  currentValue: "1",              recommendedValue: "1",              group: "security",   description: { ko: "신규 인터페이스 기본 역방향 경로 필터링", en: "Default reverse path filter for new interfaces" }, impact: { ko: "새로 추가되는 인터페이스에도 rp_filter 자동 적용", en: "Automatically applies rp_filter to newly added interfaces" } },
  { param: "net.ipv4.conf.all.accept_redirects",               currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "ICMP Redirect 수신 차단 (all)", en: "Block ICMP redirect receive (all)" }, impact: { ko: "MITM 라우팅 공격 방지", en: "Prevents MITM routing attacks" } },
  { param: "net.ipv4.conf.default.accept_redirects",           currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "ICMP Redirect 수신 차단 (default)", en: "Block ICMP redirect receive (default)" }, impact: { ko: "MITM 라우팅 공격 방지 (기본 인터페이스)", en: "Prevents MITM routing attacks on default interfaces" } },
  { param: "net.ipv4.conf.all.send_redirects",                 currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "ICMP Redirect 전송 차단 (all)", en: "Block ICMP redirect send (all)" }, impact: { ko: "라우팅 정보 유출 방지", en: "Prevents routing information leakage" } },
  { param: "net.ipv4.conf.default.send_redirects",             currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "ICMP Redirect 전송 차단 (default)", en: "Block ICMP redirect send (default)" }, impact: { ko: "라우팅 정보 유출 방지 (기본 인터페이스)", en: "Prevents routing information leakage on default interfaces" } },
  { param: "net.ipv4.conf.all.accept_source_route",            currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "Source Routing 차단 (IPv4 all)", en: "Block source routing (IPv4 all)" }, impact: { ko: "경로 조작 공격 방지", en: "Prevents route manipulation attacks" } },
  { param: "net.ipv4.conf.default.accept_source_route",        currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "Source Routing 차단 (IPv4 default)", en: "Block source routing (IPv4 default)" }, impact: { ko: "경로 조작 공격 방지 (기본 인터페이스)", en: "Prevents route manipulation attacks on default interfaces" } },
  { param: "net.ipv4.conf.all.secure_redirects",               currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "보안 ICMP Redirect 수신 차단 (all)", en: "Block secure ICMP redirect receive (all)" }, impact: { ko: "게이트웨이 경유 MITM 공격 방지", en: "Prevents gateway-relayed MITM attacks" } },
  { param: "net.ipv4.conf.default.secure_redirects",           currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "보안 ICMP Redirect 수신 차단 (default)", en: "Block secure ICMP redirect receive (default)" }, impact: { ko: "게이트웨이 경유 MITM 공격 방지 (기본 인터페이스)", en: "Prevents gateway-relayed MITM attacks on default interfaces" } },
  { param: "net.ipv4.conf.all.log_martians",                   currentValue: "1",              recommendedValue: "1",              group: "security",   description: { ko: "Martian 패킷 로깅 활성화 (all)", en: "Enable martian packet logging (all)" }, impact: { ko: "비정상 트래픽 보안 감사 지원", en: "Supports security auditing of abnormal traffic" } },
  { param: "net.ipv4.conf.default.log_martians",               currentValue: "1",              recommendedValue: "1",              group: "security",   description: { ko: "Martian 패킷 로깅 활성화 (default)", en: "Enable martian packet logging (default)" }, impact: { ko: "신규 인터페이스 비정상 트래픽 감사", en: "Audits abnormal traffic on new interfaces" } },
  { param: "net.ipv4.icmp_echo_ignore_broadcasts",             currentValue: "1",              recommendedValue: "1",              group: "security",   description: { ko: "ICMP 브로드캐스트 무시", en: "Ignore ICMP broadcast requests" }, impact: { ko: "Smurf DDoS 공격 방지", en: "Prevents Smurf DDoS attacks" } },
  { param: "net.ipv4.icmp_ignore_bogus_error_responses",       currentValue: "1",              recommendedValue: "1",              group: "security",   description: { ko: "잘못된 ICMP 오류 응답 무시", en: "Ignore bogus ICMP error responses" }, impact: { ko: "비정상 패킷으로 인한 커널 로그 노이즈 및 취약점 방지", en: "Prevents kernel log noise and vulnerabilities from malformed packets" } },
  { param: "net.ipv6.conf.all.disable_ipv6",                   currentValue: "1",              recommendedValue: "1",              group: "security",   description: { ko: "IPv6 비활성화 (all)", en: "Disable IPv6 (all)" }, impact: { ko: "IPv6 미사용 환경에서 공격 면적 감소", en: "Reduces attack surface in IPv6-unused environments" } },
  { param: "net.ipv6.conf.default.disable_ipv6",               currentValue: "1",              recommendedValue: "1",              group: "security",   description: { ko: "IPv6 비활성화 (default)", en: "Disable IPv6 (default)" }, impact: { ko: "신규 인터페이스 IPv6 자동 비활성화", en: "Automatically disables IPv6 on new interfaces" } },
  { param: "net.ipv6.conf.lo.disable_ipv6",                    currentValue: "1",              recommendedValue: "1",              group: "security",   description: { ko: "IPv6 비활성화 (loopback)", en: "Disable IPv6 (loopback)" }, impact: { ko: "루프백에서도 IPv6 스택 완전 제거", en: "Fully removes IPv6 stack even on loopback" } },
  { param: "net.ipv6.conf.all.accept_redirects",               currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "IPv6 ICMP Redirect 수신 차단 (all)", en: "Block IPv6 ICMP redirect receive (all)" }, impact: { ko: "IPv6 MITM 라우팅 공격 방지", en: "Prevents IPv6 MITM routing attacks" } },
  { param: "net.ipv6.conf.default.accept_redirects",           currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "IPv6 ICMP Redirect 수신 차단 (default)", en: "Block IPv6 ICMP redirect receive (default)" }, impact: { ko: "IPv6 MITM 라우팅 공격 방지 (기본 인터페이스)", en: "Prevents IPv6 MITM routing attacks on default interfaces" } },
  { param: "net.ipv6.conf.all.accept_source_route",            currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "IPv6 Source Routing 차단 (all)", en: "Block IPv6 source routing (all)" }, impact: { ko: "IPv6 경로 조작 공격 방지", en: "Prevents IPv6 route manipulation attacks" } },
  { param: "net.ipv6.conf.default.accept_source_route",        currentValue: "0",              recommendedValue: "0",              group: "security",   description: { ko: "IPv6 Source Routing 차단 (default)", en: "Block IPv6 source routing (default)" }, impact: { ko: "IPv6 경로 조작 공격 방지 (기본 인터페이스)", en: "Prevents IPv6 route manipulation attacks on default interfaces" } },
  { param: "kernel.panic",                                      currentValue: "10",             recommendedValue: "10",             group: "security",   description: { ko: "커널 패닉 후 자동 재부팅 대기(초)", en: "Auto-reboot delay after kernel panic (seconds)" }, impact: { ko: "장애 노드 자동 복구", en: "Enables automatic recovery of failed nodes" } },
  { param: "kernel.panic_on_oops",                             currentValue: "1",              recommendedValue: "1",              group: "security",   description: { ko: "커널 Oops 시 패닉 처리", en: "Panic on kernel oops" }, impact: { ko: "커널 상태 불안정 시 빠른 복구", en: "Fast recovery when kernel state is unstable" } },
  // ── Resource ────────────────────────────────────────────────────────────
  { param: "vm.swappiness",                                     currentValue: "0",              recommendedValue: "0",              group: "resource",   description: { ko: "스왑 비활성화 (K8s 필수)", en: "Disable swap (K8s required)" }, impact: { ko: "컨테이너 예측 가능한 메모리 동작", en: "Ensures predictable memory behavior for containers" } },
  { param: "vm.overcommit_memory",                              currentValue: "1",              recommendedValue: "1",              group: "resource",   description: { ko: "메모리 오버커밋 허용", en: "Allow memory overcommit" }, impact: { ko: "K8s 메모리 할당 예측 가능성 향상", en: "Improves K8s memory allocation predictability" } },
  { param: "vm.max_map_count",                                  currentValue: "65530",          recommendedValue: "262144",         group: "resource",   description: { ko: "프로세스당 메모리 맵 최대 수", en: "Max memory mappings per process" }, impact: { ko: "Elasticsearch·JVM 앱 실행 보장", en: "Guarantees Elasticsearch and JVM app execution" } },
  { param: "vm.dirty_ratio",                                    currentValue: "40",             recommendedValue: "40",             group: "resource",   description: { ko: "Dirty 페이지 최대 비율 (%)", en: "Max dirty page ratio (%)" }, impact: { ko: "I/O 집약적 워크로드 쓰기 버퍼링", en: "Write buffering for I/O-intensive workloads" } },
  { param: "vm.dirty_background_ratio",                         currentValue: "10",             recommendedValue: "10",             group: "resource",   description: { ko: "백그라운드 Dirty 페이지 플러시 임계값 (%)", en: "Background dirty page flush threshold (%)" }, impact: { ko: "주기적 쓰기 백그라운드 처리로 I/O 스파이크 완화", en: "Mitigates I/O spikes via periodic background write flushing" } },
  { param: "vm.min_free_kbytes",                                currentValue: "131072",         recommendedValue: "131072",         group: "resource",   description: { ko: "최소 여유 메모리 (커널 할당용)", en: "Minimum free memory (for kernel allocation)" }, impact: { ko: "메모리 고갈 시 OOM 예방", en: "Prevents OOM when memory is exhausted" } },
  { param: "vm.panic_on_oom",                                   currentValue: "0",              recommendedValue: "0",              group: "resource",   description: { ko: "OOM 발생 시 패닉 방지", en: "Disable panic on OOM" }, impact: { ko: "OOM killer가 K8s eviction과 충돌 방지", en: "Prevents OOM killer from conflicting with K8s eviction" } },
  { param: "kernel.pid_max",                                    currentValue: "4194304",        recommendedValue: "4194304",        group: "resource",   description: { ko: "최대 프로세스 ID 수", en: "Max process ID count" }, impact: { ko: "대규모 컨테이너 환경 PID 고갈 방지", en: "Prevents PID exhaustion in large container environments" } },
  { param: "kernel.sched_min_granularity_ns",                   currentValue: "1000000",        recommendedValue: "1000000",        group: "resource",   description: { ko: "CFS 스케줄러 최소 실행 단위 (1ms)", en: "CFS scheduler minimum granularity (1ms)" }, impact: { ko: "컨테이너 간 공정한 CPU 분배", en: "Fair CPU distribution across containers" } },
  { param: "kernel.sched_wakeup_granularity_ns",                currentValue: "500000",         recommendedValue: "500000",         group: "resource",   description: { ko: "CFS wake-up 분리 임계값 (0.5ms)", en: "CFS wakeup preemption granularity (0.5ms)" }, impact: { ko: "저지연 워크로드 스케줄링 최적화", en: "Optimizes scheduling for low-latency workloads" } },
  // ── Filesystem ──────────────────────────────────────────────────────────
  { param: "fs.file-max",                                       currentValue: "2097152",        recommendedValue: "2097152",        group: "filesystem", description: { ko: "시스템 전체 파일 디스크립터 최대 수", en: "Max file descriptors system-wide" }, impact: { ko: "고부하 I/O 환경 파일 핸들 고갈 방지", en: "Prevents file handle exhaustion under high I/O load" } },
  { param: "fs.inotify.max_user_watches",                       currentValue: "524288",         recommendedValue: "524288",         group: "filesystem", description: { ko: "inotify 파일 감시 최대 수", en: "Max inotify watches per user" }, impact: { ko: "파일 변경 감지 실패(ENOSPC) 방지", en: "Prevents inotify watch exhaustion (ENOSPC)" } },
  { param: "fs.inotify.max_user_instances",                     currentValue: "8192",           recommendedValue: "8192",           group: "filesystem", description: { ko: "inotify 인스턴스 최대 수", en: "Max inotify instances per user" }, impact: { ko: "컨테이너 파일 감시 안정성", en: "Ensures stable file watching for containers" } },
]

export const K8S_RECOMMENDED_KERNEL_PARAMS: KernelParamInfo[] = RAW_PARAMS.map((p) => ({
  ...p,
  configHint: hint(p.param, p.recommendedValue),
}))
